# Project information
site_name: 西电摆烂档案馆
site_url: https://dreamskycx.github.io/xduresources/
site_author: Dreamskycx


# Repository
repo_name: dreamskycx/xduresources
repo_url: https://github.com/dreamskycx/xduresources

# Copyright
copyright: Copyright &copy; 2022 - 2023 Dreamskycx

theme:

  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换夜晚

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换白天
      primary: indigo

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  logo: #logo.jpg
  favicon: #logo.jpg

plugins:
  - search:
      separator: '[\s\u200b\-]'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dreamskycx/waterbox
      name: 西电档案馆

# Page tree
nav:
  - 档案馆: index.md
